
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.Table table3;

	private global::Gtk.Button btnCambiarFondo;

	private global::Gtk.Button btnComida;

	private global::Gtk.Button btnInsertar;

	private global::Gtk.Button btnMostrar;

	private global::Gtk.Button btnOpenWinComida;

	private global::Gtk.Button btnOrdenar;

	private global::Gtk.Button btnSalir;

	private global::Gtk.Label GtkLabel6;

	private global::Gtk.Image image1;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Table table1;

	private global::Gtk.Calendar calendar1;

	private global::Gtk.Entry entryComida;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.SpinButton spinbuttonID;

	private global::Gtk.Table table2;

	private global::Gtk.Label label4;

	private global::Gtk.Label label5;

	private global::Gtk.SpinButton spinhora;

	private global::Gtk.SpinButton spinmin;

	private global::Gtk.Label GtkLabel7;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView Tabla;

	private global::Gtk.Label GtkLabel8;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.Table table4;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment4;

	private global::Gtk.Table table5;

	private global::Gtk.RadioButton rdbfecha;

	private global::Gtk.RadioButton rdbimagen;

	private global::Gtk.RadioButton rdbnombre;

	private global::Gtk.RadioButton rdbregistro;

	private global::Gtk.Label GtkLabel16;

	private global::Gtk.Frame frame6;

	private global::Gtk.Alignment GtkAlignment5;

	private global::Gtk.Table table6;

	private global::Gtk.RadioButton rdbAsc;

	private global::Gtk.RadioButton rdbDesc;

	private global::Gtk.Label GtkLabel11;

	private global::Gtk.Label GtkLabel17;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Registro de comida");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "stock_internet", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(4)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.btnCambiarFondo = new global::Gtk.Button();
		this.btnCambiarFondo.CanFocus = true;
		this.btnCambiarFondo.Name = "btnCambiarFondo";
		this.btnCambiarFondo.UseUnderline = true;
		this.btnCambiarFondo.Label = global::Mono.Unix.Catalog.GetString("Cambiar fondo");
		this.table3.Add(this.btnCambiarFondo);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.btnCambiarFondo]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnComida = new global::Gtk.Button();
		this.btnComida.CanFocus = true;
		this.btnComida.Name = "btnComida";
		this.btnComida.UseUnderline = true;
		this.btnComida.Label = global::Mono.Unix.Catalog.GetString("Crear\nComida");
		this.table3.Add(this.btnComida);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.btnComida]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnInsertar = new global::Gtk.Button();
		this.btnInsertar.CanFocus = true;
		this.btnInsertar.Name = "btnInsertar";
		this.btnInsertar.UseUnderline = true;
		this.btnInsertar.Label = global::Mono.Unix.Catalog.GetString("Insertar");
		this.table3.Add(this.btnInsertar);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.btnInsertar]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnMostrar = new global::Gtk.Button();
		this.btnMostrar.CanFocus = true;
		this.btnMostrar.Name = "btnMostrar";
		this.btnMostrar.UseUnderline = true;
		this.btnMostrar.Label = global::Mono.Unix.Catalog.GetString("Mostrar");
		this.table3.Add(this.btnMostrar);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.btnMostrar]));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnOpenWinComida = new global::Gtk.Button();
		this.btnOpenWinComida.CanFocus = true;
		this.btnOpenWinComida.Name = "btnOpenWinComida";
		this.btnOpenWinComida.UseUnderline = true;
		this.btnOpenWinComida.Label = global::Mono.Unix.Catalog.GetString("¿Que Comer?");
		this.table3.Add(this.btnOpenWinComida);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.btnOpenWinComida]));
		w6.LeftAttach = ((uint)(3));
		w6.RightAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnOrdenar = new global::Gtk.Button();
		this.btnOrdenar.CanFocus = true;
		this.btnOrdenar.Name = "btnOrdenar";
		this.btnOrdenar.UseUnderline = true;
		this.btnOrdenar.Label = global::Mono.Unix.Catalog.GetString("Ordenar");
		this.table3.Add(this.btnOrdenar);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.btnOrdenar]));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnSalir = new global::Gtk.Button();
		this.btnSalir.CanFocus = true;
		this.btnSalir.Name = "btnSalir";
		this.btnSalir.UseUnderline = true;
		this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.table3.Add(this.btnSalir);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.btnSalir]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(3));
		w8.RightAttach = ((uint)(4));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment1.Add(this.table3);
		this.frame2.Add(this.GtkAlignment1);
		this.GtkLabel6 = new global::Gtk.Label();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Botones</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel6;
		this.fixed1.Add(this.frame2);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame2]));
		w11.X = 43;
		w11.Y = 353;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.fixed1.Add(this.image1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image1]));
		w12.X = 649;
		w12.Y = 51;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.calendar1 = new global::Gtk.Calendar();
		this.calendar1.CanFocus = true;
		this.calendar1.Name = "calendar1";
		this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.table1.Add(this.calendar1);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.calendar1]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryComida = new global::Gtk.Entry();
		this.entryComida.CanFocus = true;
		this.entryComida.Name = "entryComida";
		this.entryComida.Text = global::Mono.Unix.Catalog.GetString("0");
		this.entryComida.IsEditable = false;
		this.entryComida.InvisibleChar = '•';
		this.table1.Add(this.entryComida);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.entryComida]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("ImagenID");
		this.table1.Add(this.label1);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("NombreID");
		this.table1.Add(this.label2);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w16.TopAttach = ((uint)(1));
		w16.BottomAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de compra");
		this.table1.Add(this.label3);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
		w17.TopAttach = ((uint)(2));
		w17.BottomAttach = ((uint)(3));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbuttonID = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbuttonID.CanFocus = true;
		this.spinbuttonID.Name = "spinbuttonID";
		this.spinbuttonID.Adjustment.PageIncrement = 10D;
		this.spinbuttonID.ClimbRate = 1D;
		this.spinbuttonID.Numeric = true;
		this.table1.Add(this.spinbuttonID);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.spinbuttonID]));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("hora");
		this.table2.Add(this.label4);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2[this.label4]));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("minutos");
		this.table2.Add(this.label5);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2[this.label5]));
		w20.LeftAttach = ((uint)(1));
		w20.RightAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.spinhora = new global::Gtk.SpinButton(0D, 23D, 1D);
		this.spinhora.CanFocus = true;
		this.spinhora.Name = "spinhora";
		this.spinhora.Adjustment.PageIncrement = 10D;
		this.spinhora.ClimbRate = 1D;
		this.spinhora.Numeric = true;
		this.table2.Add(this.spinhora);
		global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2[this.spinhora]));
		w21.TopAttach = ((uint)(1));
		w21.BottomAttach = ((uint)(2));
		w21.XOptions = ((global::Gtk.AttachOptions)(4));
		w21.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.spinmin = new global::Gtk.SpinButton(0D, 59D, 1D);
		this.spinmin.CanFocus = true;
		this.spinmin.Name = "spinmin";
		this.spinmin.Adjustment.PageIncrement = 10D;
		this.spinmin.ClimbRate = 1D;
		this.spinmin.Numeric = true;
		this.table2.Add(this.spinmin);
		global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2[this.spinmin]));
		w22.TopAttach = ((uint)(1));
		w22.BottomAttach = ((uint)(2));
		w22.LeftAttach = ((uint)(1));
		w22.RightAttach = ((uint)(2));
		w22.XOptions = ((global::Gtk.AttachOptions)(4));
		w22.YOptions = ((global::Gtk.AttachOptions)(4));
		this.table1.Add(this.table2);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table1[this.table2]));
		w23.TopAttach = ((uint)(2));
		w23.BottomAttach = ((uint)(3));
		w23.LeftAttach = ((uint)(2));
		w23.RightAttach = ((uint)(3));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add(this.table1);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel7 = new global::Gtk.Label();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>INFORMACION</b>");
		this.GtkLabel7.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel7;
		this.fixed1.Add(this.frame1);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame1]));
		w26.X = 41;
		w26.Y = 29;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Tabla = new global::Gtk.NodeView();
		this.Tabla.WidthRequest = 800;
		this.Tabla.HeightRequest = 200;
		this.Tabla.CanFocus = true;
		this.Tabla.Name = "Tabla";
		this.GtkScrolledWindow.Add(this.Tabla);
		this.GtkAlignment2.Add(this.GtkScrolledWindow);
		this.frame3.Add(this.GtkAlignment2);
		this.GtkLabel8 = new global::Gtk.Label();
		this.GtkLabel8.Name = "GtkLabel8";
		this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Tabla</b>");
		this.GtkLabel8.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel8;
		this.fixed1.Add(this.frame3);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame3]));
		w30.X = 5;
		w30.Y = 491;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame4 = new global::Gtk.Frame();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.table4 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.frame5 = new global::Gtk.Frame();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.table5 = new global::Gtk.Table(((uint)(4)), ((uint)(1)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.rdbfecha = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Fecha"));
		this.rdbfecha.CanFocus = true;
		this.rdbfecha.Name = "rdbfecha";
		this.rdbfecha.Active = true;
		this.rdbfecha.DrawIndicator = true;
		this.rdbfecha.UseUnderline = true;
		this.rdbfecha.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.table5.Add(this.rdbfecha);
		global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table5[this.rdbfecha]));
		w31.TopAttach = ((uint)(3));
		w31.BottomAttach = ((uint)(4));
		w31.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.rdbimagen = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Imagen"));
		this.rdbimagen.CanFocus = true;
		this.rdbimagen.Name = "rdbimagen";
		this.rdbimagen.DrawIndicator = true;
		this.rdbimagen.UseUnderline = true;
		this.rdbimagen.Group = this.rdbfecha.Group;
		this.table5.Add(this.rdbimagen);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table5[this.rdbimagen]));
		w32.TopAttach = ((uint)(1));
		w32.BottomAttach = ((uint)(2));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.rdbnombre = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Nombre"));
		this.rdbnombre.CanFocus = true;
		this.rdbnombre.Name = "rdbnombre";
		this.rdbnombre.DrawIndicator = true;
		this.rdbnombre.UseUnderline = true;
		this.rdbnombre.Group = this.rdbfecha.Group;
		this.table5.Add(this.rdbnombre);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table5[this.rdbnombre]));
		w33.TopAttach = ((uint)(2));
		w33.BottomAttach = ((uint)(3));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.rdbregistro = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Id registro"));
		this.rdbregistro.CanFocus = true;
		this.rdbregistro.Name = "rdbregistro";
		this.rdbregistro.DrawIndicator = true;
		this.rdbregistro.UseUnderline = true;
		this.rdbregistro.Group = this.rdbfecha.Group;
		this.table5.Add(this.rdbregistro);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table5[this.rdbregistro]));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment4.Add(this.table5);
		this.frame5.Add(this.GtkAlignment4);
		this.GtkLabel16 = new global::Gtk.Label();
		this.GtkLabel16.Name = "GtkLabel16";
		this.GtkLabel16.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Tipo</b>");
		this.GtkLabel16.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel16;
		this.table4.Add(this.frame5);
		global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table4[this.frame5]));
		w37.XOptions = ((global::Gtk.AttachOptions)(4));
		w37.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.frame6 = new global::Gtk.Frame();
		this.frame6.Name = "frame6";
		this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.table6 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
		this.table6.Name = "table6";
		this.table6.RowSpacing = ((uint)(6));
		this.table6.ColumnSpacing = ((uint)(6));
		// Container child table6.Gtk.Table+TableChild
		this.rdbAsc = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Ascendente"));
		this.rdbAsc.CanFocus = true;
		this.rdbAsc.Name = "rdbAsc";
		this.rdbAsc.Active = true;
		this.rdbAsc.DrawIndicator = true;
		this.rdbAsc.UseUnderline = true;
		this.rdbAsc.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.table6.Add(this.rdbAsc);
		global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table6[this.rdbAsc]));
		w38.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table6.Gtk.Table+TableChild
		this.rdbDesc = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Descendente"));
		this.rdbDesc.CanFocus = true;
		this.rdbDesc.Name = "rdbDesc";
		this.rdbDesc.DrawIndicator = true;
		this.rdbDesc.UseUnderline = true;
		this.rdbDesc.Group = this.rdbAsc.Group;
		this.table6.Add(this.rdbDesc);
		global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table6[this.rdbDesc]));
		w39.TopAttach = ((uint)(1));
		w39.BottomAttach = ((uint)(2));
		w39.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment5.Add(this.table6);
		this.frame6.Add(this.GtkAlignment5);
		this.GtkLabel11 = new global::Gtk.Label();
		this.GtkLabel11.Name = "GtkLabel11";
		this.GtkLabel11.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Orden</b>");
		this.GtkLabel11.UseMarkup = true;
		this.frame6.LabelWidget = this.GtkLabel11;
		this.table4.Add(this.frame6);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table4[this.frame6]));
		w42.TopAttach = ((uint)(1));
		w42.BottomAttach = ((uint)(2));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment3.Add(this.table4);
		this.frame4.Add(this.GtkAlignment3);
		this.GtkLabel17 = new global::Gtk.Label();
		this.GtkLabel17.Name = "GtkLabel17";
		this.GtkLabel17.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Ordenar</b>");
		this.GtkLabel17.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel17;
		this.fixed1.Add(this.frame4);
		global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame4]));
		w45.X = 614;
		w45.Y = 210;
		w1.Add(this.fixed1);
		this.scrolledwindow1.Add(w1);
		this.Add(this.scrolledwindow1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 873;
		this.DefaultHeight = 554;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnSalir.Clicked += new global::System.EventHandler(this.btnSalir_Clicked);
		this.btnOrdenar.Clicked += new global::System.EventHandler(this.ordenar_clicked);
		this.btnOpenWinComida.Clicked += new global::System.EventHandler(this.AbrirWinComida);
		this.btnMostrar.Clicked += new global::System.EventHandler(this.btnMostrar_Clicked);
		this.btnInsertar.Clicked += new global::System.EventHandler(this.btnInsertar_Clicked);
		this.btnComida.Clicked += new global::System.EventHandler(this.Btnabrirventanacomida_clicked);
		this.btnCambiarFondo.Clicked += new global::System.EventHandler(this.CambiarFondo_clicked);
		this.spinbuttonID.Changed += new global::System.EventHandler(this.spinimagenid_chenged);
	}
}
