
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.Frame frame1;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.Table table1;

	private global::Gtk.Calendar calendar1;

	private global::Gtk.Entry entryComida;

	private global::Gtk.Label label1;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.SpinButton spinbuttonID;

	private global::Gtk.Label GtkLabel;

	private global::Gtk.Image image1;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.Table table3;

	private global::Gtk.Button btnInsertar;

	private global::Gtk.Button btnMostrar;

	private global::Gtk.Button btnSalir;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Label GtkLabel1;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView Tabla;

	private global::Gtk.Label GtkLabel7;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Registro de comida");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "stock_internet", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w1 = new global::Gtk.Viewport();
		w1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame1 = new global::Gtk.Frame();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table(((uint)(3)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.calendar1 = new global::Gtk.Calendar();
		this.calendar1.CanFocus = true;
		this.calendar1.Name = "calendar1";
		this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.table1.Add(this.calendar1);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.calendar1]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryComida = new global::Gtk.Entry();
		this.entryComida.CanFocus = true;
		this.entryComida.Name = "entryComida";
		this.entryComida.IsEditable = true;
		this.entryComida.InvisibleChar = '•';
		this.table1.Add(this.entryComida);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.entryComida]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("ImagenID");
		this.table1.Add(this.label1);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre comida");
		this.table1.Add(this.label2);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.label2]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de compra");
		this.table1.Add(this.label3);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.spinbuttonID = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbuttonID.CanFocus = true;
		this.spinbuttonID.Name = "spinbuttonID";
		this.spinbuttonID.Adjustment.PageIncrement = 10D;
		this.spinbuttonID.ClimbRate = 1D;
		this.spinbuttonID.Numeric = true;
		this.table1.Add(this.spinbuttonID);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.spinbuttonID]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add(this.table1);
		this.frame1.Add(this.GtkAlignment);
		this.GtkLabel = new global::Gtk.Label();
		this.GtkLabel.Name = "GtkLabel";
		this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>INFORMACION</b>");
		this.GtkLabel.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel;
		this.fixed1.Add(this.frame1);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame1]));
		w10.X = 41;
		w10.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.image1 = new global::Gtk.Image();
		this.image1.Name = "image1";
		this.fixed1.Add(this.image1);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.image1]));
		w11.X = 464;
		w11.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.table3 = new global::Gtk.Table(((uint)(2)), ((uint)(4)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.btnInsertar = new global::Gtk.Button();
		this.btnInsertar.CanFocus = true;
		this.btnInsertar.Name = "btnInsertar";
		this.btnInsertar.UseUnderline = true;
		this.btnInsertar.Label = global::Mono.Unix.Catalog.GetString("Insertar");
		this.table3.Add(this.btnInsertar);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table3[this.btnInsertar]));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnMostrar = new global::Gtk.Button();
		this.btnMostrar.CanFocus = true;
		this.btnMostrar.Name = "btnMostrar";
		this.btnMostrar.UseUnderline = true;
		this.btnMostrar.Label = global::Mono.Unix.Catalog.GetString("Mostrar");
		this.table3.Add(this.btnMostrar);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3[this.btnMostrar]));
		w13.LeftAttach = ((uint)(1));
		w13.RightAttach = ((uint)(2));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.btnSalir = new global::Gtk.Button();
		this.btnSalir.CanFocus = true;
		this.btnSalir.Name = "btnSalir";
		this.btnSalir.UseUnderline = true;
		this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
		this.table3.Add(this.btnSalir);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3[this.btnSalir]));
		w14.TopAttach = ((uint)(1));
		w14.BottomAttach = ((uint)(2));
		w14.LeftAttach = ((uint)(3));
		w14.RightAttach = ((uint)(4));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button3);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3[this.button3]));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.table3.Add(this.button4);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3[this.button4]));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment1.Add(this.table3);
		this.frame2.Add(this.GtkAlignment1);
		this.GtkLabel1 = new global::Gtk.Label();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Botones</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel1;
		this.fixed1.Add(this.frame2);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame2]));
		w19.X = 43;
		w19.Y = 353;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.Tabla = new global::Gtk.NodeView();
		this.Tabla.WidthRequest = 800;
		this.Tabla.HeightRequest = 200;
		this.Tabla.CanFocus = true;
		this.Tabla.Name = "Tabla";
		this.GtkScrolledWindow.Add(this.Tabla);
		this.GtkAlignment2.Add(this.GtkScrolledWindow);
		this.frame3.Add(this.GtkAlignment2);
		this.GtkLabel7 = new global::Gtk.Label();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Tabla</b>");
		this.GtkLabel7.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel7;
		this.fixed1.Add(this.frame3);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.frame3]));
		w23.X = 51;
		w23.Y = 482;
		w1.Add(this.fixed1);
		this.scrolledwindow1.Add(w1);
		this.Add(this.scrolledwindow1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 789;
		this.DefaultHeight = 528;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnSalir.Clicked += new global::System.EventHandler(this.btnSalir_Clicked);
		this.btnMostrar.Clicked += new global::System.EventHandler(this.btnMostrar_Clicked);
	}
}
