
// This file has been generated by the GUI designer. Do not modify.
namespace RegisComida
{
	public partial class Window1
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RegisComida.Window1
			this.Name = "RegisComida.Window1";
			this.Title = global::Mono.Unix.Catalog.GetString("Window1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
