
// This file has been generated by the GUI designer. Do not modify.
namespace RegisComida
{
	public partial class Widget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget RegisComida.Widget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "RegisComida.Widget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
